### ISSUE TITLE
Add autocomplete and linting?

### ISSUE THREAD

**Issue by philipgiuliani** [torrick/vscode-elixir-lang#1]
Hi! Are you planning to add autocompletion and linter support? Would be awesome! :)

**Comment by torrick** [comment]
@philipgiuliani sure I'd be happy to.  I'm a bit of a newbie on the vscode extension development but I'll certainly take a stab at it.  As always pull requests are always appreciated :)

**Comment by torrick** [comment]
Actually, this guy: https://github.com/mat-mcloughlin/vscode-elixir/pull/5 is pretty close to what you want.  I'll probably remove my extension and send people there.  vscode-elixir is gaining lots of traction and it's probably better to have one good vscode extension than a bunch of okay ones.
